/**
 * NSI.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuditTrailDomain } from './auditTrailDomain';
import { DeviceStatusDomain } from './deviceStatusDomain';
import { DeviceTypeDomain } from './deviceTypeDomain';


export interface DeviceDomain {
    deviceId?: number;
    identifier?: string;
    description?: string;
    name?: string;
    isActive?: boolean;
    isDeleted?: boolean;
    deviceTypeId?: number;
    deviceStatusId?: number;
    deviceType?: DeviceTypeDomain;
    deviceStatus?: DeviceStatusDomain;
    deviceImage?: string;
    auditTrail?: AuditTrailDomain;
    id?: number;
    tenantId?: number;
}
