/**
 * NSI.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmailRecipientDomain } from './emailRecipientDomain';


export interface EmailRecipientTypeDomain {
    name?: string;
    code?: string;
    emailRecipients?: Array<EmailRecipientDomain>;
    id?: number;
    tenantId?: number;
}
