/**
 * NSI.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmailMessageDomain } from './emailMessageDomain';
import { EmailRecipientTypeDomain } from './emailRecipientTypeDomain';


export interface EmailRecipientDomain {
    emailAddress?: string;
    emaiMessagelId?: number;
    emailRecipientTypeId?: number;
    emailMessage?: EmailMessageDomain;
    emailRecipientType?: EmailRecipientTypeDomain;
    id?: number;
    tenantId?: number;
}
