/**
 * NSI.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DeviceDomain } from './deviceDomain';
import { IncidentPriorityDomain } from './incidentPriorityDomain';
import { IncidentStatusDomain } from './incidentStatusDomain';
import { IncidentTypeDomain } from './incidentTypeDomain';
import { TenantDomain } from './tenantDomain';
import { UserDomain } from './userDomain';


export interface IncidentDomain {
    incidentId?: number;
    dateCreated?: Date;
    createdBy?: number;
    modifiedBy?: number;
    dateModified?: Date;
    tenant?: TenantDomain;
    incidentStatus?: IncidentStatusDomain;
    device?: DeviceDomain;
    priority?: IncidentPriorityDomain;
    incidentType?: IncidentTypeDomain;
    reporter?: UserDomain;
    assignee?: UserDomain;
    id?: number;
    tenantId?: number;
}
