/**
 * NSI.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SortCriteria {
    columnName?: string;
    order?: SortCriteria.OrderEnum;
    priority?: number;
}
export namespace SortCriteria {
    export type OrderEnum = 0 | 1 | -1;
    export const OrderEnum = {
        NUMBER_0: 0 as OrderEnum,
        NUMBER_1: 1 as OrderEnum,
        NUMBER_MINUS_1: -1 as OrderEnum
    }
}
