/**
 * NSI.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DocumentDomain } from './documentDomain';


export interface StorageTypeDomain {
    storageTypeId?: number;
    isActive?: boolean;
    name?: string;
    code?: string;
    documents?: Array<DocumentDomain>;
}
