/**
 * NSI.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface WebNotificationDomain {
    seen?: boolean;
    dateSeen?: Date;
    notificationId?: number;
    userInfoId?: number;
    userTenantId?: number;
    title?: string;
    content?: string;
    externalId?: string;
    dateCreated?: Date;
    dateModified?: Date;
    notificationStatusId?: number;
    notificationTypeId?: number;
    id?: number;
    tenantId?: number;
}
