export * from './action.service';
import { ActionService } from './action.service';
export * from './attachment.service';
import { AttachmentService } from './attachment.service';
export * from './device.service';
import { DeviceService } from './device.service';
export * from './devicePing.service';
import { DevicePingService } from './devicePing.service';
export * from './deviceType.service';
import { DeviceTypeService } from './deviceType.service';
export * from './document.service';
import { DocumentService } from './document.service';
export * from './documentGenerator.service';
import { DocumentGeneratorService } from './documentGenerator.service';
export * from './emailMessage.service';
import { EmailMessageService } from './emailMessage.service';
export * from './emailRecipient.service';
import { EmailRecipientService } from './emailRecipient.service';
export * from './emailRecipientType.service';
import { EmailRecipientTypeService } from './emailRecipientType.service';
export * from './fakePing.service';
import { FakePingService } from './fakePing.service';
export * from './fileType.service';
import { FileTypeService } from './fileType.service';
export * from './incident.service';
import { IncidentService } from './incident.service';
export * from './incidentPriority.service';
import { IncidentPriorityService } from './incidentPriority.service';
export * from './incidentSettlement.service';
import { IncidentSettlementService } from './incidentSettlement.service';
export * from './incidentStatus.service';
import { IncidentStatusService } from './incidentStatus.service';
export * from './incidentType.service';
import { IncidentTypeService } from './incidentType.service';
export * from './incidentWorkOrder.service';
import { IncidentWorkOrderService } from './incidentWorkOrder.service';
export * from './language.service';
import { LanguageService } from './language.service';
export * from './module.service';
import { ModuleService } from './module.service';
export * from './notification.service';
import { NotificationService } from './notification.service';
export * from './notificationStatus.service';
import { NotificationStatusService } from './notificationStatus.service';
export * from './notificationType.service';
import { NotificationTypeService } from './notificationType.service';
export * from './notificationUser.service';
import { NotificationUserService } from './notificationUser.service';
export * from './permission.service';
import { PermissionService } from './permission.service';
export * from './property.service';
import { PropertyService } from './property.service';
export * from './reporting.service';
import { ReportingService } from './reporting.service';
export * from './role.service';
import { RoleService } from './role.service';
export * from './roleMember.service';
import { RoleMemberService } from './roleMember.service';
export * from './rolePermission.service';
import { RolePermissionService } from './rolePermission.service';
export * from './rule.service';
import { RuleService } from './rule.service';
export * from './sms.service';
import { SmsService } from './sms.service';
export * from './storageType.service';
import { StorageTypeService } from './storageType.service';
export * from './templateManagement.service';
import { TemplateManagementService } from './templateManagement.service';
export * from './tenant.service';
import { TenantService } from './tenant.service';
export * from './test.service';
import { TestService } from './test.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './webNotification.service';
import { WebNotificationService } from './webNotification.service';
export const APIS = [ActionService, AttachmentService, DeviceService, DevicePingService, DeviceTypeService, DocumentService, DocumentGeneratorService, EmailMessageService, EmailRecipientService, EmailRecipientTypeService, FakePingService, FileTypeService, IncidentService, IncidentPriorityService, IncidentSettlementService, IncidentStatusService, IncidentTypeService, IncidentWorkOrderService, LanguageService, ModuleService, NotificationService, NotificationStatusService, NotificationTypeService, NotificationUserService, PermissionService, PropertyService, ReportingService, RoleService, RoleMemberService, RolePermissionService, RuleService, SmsService, StorageTypeService, TemplateManagementService, TenantService, TestService, UserService, WebNotificationService];
