/**
 * NSI.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { AddEmailRecipientRequest } from '../model/addEmailRecipientRequest';
import { AddEmailRecipientResponse } from '../model/addEmailRecipientResponse';
import { DeleteEmailRecipientResponse } from '../model/deleteEmailRecipientResponse';
import { GetAllEmailRecipientsResponse } from '../model/getAllEmailRecipientsResponse';
import { GetEmailRecipientResponse } from '../model/getEmailRecipientResponse';
import { SearchEmailRecipientRequest } from '../model/searchEmailRecipientRequest';
import { SearchEmailRecipientResponse } from '../model/searchEmailRecipientResponse';
import { UpdateEmailRecipientRequest } from '../model/updateEmailRecipientRequest';
import { UpdateEmailRecipientResponse } from '../model/updateEmailRecipientResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class EmailRecipientService {

    protected basePath = 'https://localhost:44349';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Adds new email recipient
     * 
     * @param request {NSI.DataContracts.Notifications.EmailRecipient.AddEmailRecipientRequest}
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailRecipientAddEmailRecipient(request: AddEmailRecipientRequest, observe?: 'body', reportProgress?: boolean): Observable<AddEmailRecipientResponse>;
    public emailRecipientAddEmailRecipient(request: AddEmailRecipientRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AddEmailRecipientResponse>>;
    public emailRecipientAddEmailRecipient(request: AddEmailRecipientRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AddEmailRecipientResponse>>;
    public emailRecipientAddEmailRecipient(request: AddEmailRecipientRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling emailRecipientAddEmailRecipient.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<AddEmailRecipientResponse>(`${this.basePath}/api/EmailRecipient/AddEmailRecipient`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Deletes email recipient
     * 
     * @param emailRecipientId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailRecipientDelete(emailRecipientId: number, observe?: 'body', reportProgress?: boolean): Observable<DeleteEmailRecipientResponse>;
    public emailRecipientDelete(emailRecipientId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DeleteEmailRecipientResponse>>;
    public emailRecipientDelete(emailRecipientId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DeleteEmailRecipientResponse>>;
    public emailRecipientDelete(emailRecipientId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (emailRecipientId === null || emailRecipientId === undefined) {
            throw new Error('Required parameter emailRecipientId was null or undefined when calling emailRecipientDelete.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (emailRecipientId !== undefined) {
            queryParameters = queryParameters.set('emailRecipientId', <any>emailRecipientId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<DeleteEmailRecipientResponse>(`${this.basePath}/api/EmailRecipient/Delete`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves all email recipients
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailRecipientGetAllEmailRecipients(observe?: 'body', reportProgress?: boolean): Observable<GetAllEmailRecipientsResponse>;
    public emailRecipientGetAllEmailRecipients(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetAllEmailRecipientsResponse>>;
    public emailRecipientGetAllEmailRecipients(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetAllEmailRecipientsResponse>>;
    public emailRecipientGetAllEmailRecipients(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];

        return this.httpClient.get<GetAllEmailRecipientsResponse>(`${this.basePath}/api/EmailRecipient/GetAllEmailRecipients`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves a single email recipient by provided ID in request
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailRecipientGetEmailRecipient(id: number, observe?: 'body', reportProgress?: boolean): Observable<GetEmailRecipientResponse>;
    public emailRecipientGetEmailRecipient(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetEmailRecipientResponse>>;
    public emailRecipientGetEmailRecipient(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetEmailRecipientResponse>>;
    public emailRecipientGetEmailRecipient(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling emailRecipientGetEmailRecipient.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<GetEmailRecipientResponse>(`${this.basePath}/api/EmailRecipient/GetEmailRecipient/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Searches email recipients. If no parameters have been provided in request, returns all email recipients.
     * 
     * @param request 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailRecipientSearchEmailRecipients(request: SearchEmailRecipientRequest, observe?: 'body', reportProgress?: boolean): Observable<SearchEmailRecipientResponse>;
    public emailRecipientSearchEmailRecipients(request: SearchEmailRecipientRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SearchEmailRecipientResponse>>;
    public emailRecipientSearchEmailRecipients(request: SearchEmailRecipientRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SearchEmailRecipientResponse>>;
    public emailRecipientSearchEmailRecipients(request: SearchEmailRecipientRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling emailRecipientSearchEmailRecipients.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<SearchEmailRecipientResponse>(`${this.basePath}/api/EmailRecipient/SearchEmailRecipients`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Updates email recipient
     * 
     * @param request {NSI.DataContracts.Notifications.EmailRecipient.UpdateEmailRecipientRequest}
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailRecipientUpdateEmailRecipient(request: UpdateEmailRecipientRequest, observe?: 'body', reportProgress?: boolean): Observable<UpdateEmailRecipientResponse>;
    public emailRecipientUpdateEmailRecipient(request: UpdateEmailRecipientRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UpdateEmailRecipientResponse>>;
    public emailRecipientUpdateEmailRecipient(request: UpdateEmailRecipientRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UpdateEmailRecipientResponse>>;
    public emailRecipientUpdateEmailRecipient(request: UpdateEmailRecipientRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling emailRecipientUpdateEmailRecipient.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<UpdateEmailRecipientResponse>(`${this.basePath}/api/EmailRecipient/UpdateEmailRecipient`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
