/**
 * NSI.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { AddEmailMessageRequest } from '../model/addEmailMessageRequest';
import { AddEmailMessageResponse } from '../model/addEmailMessageResponse';
import { DeleteEmailMessageResponse } from '../model/deleteEmailMessageResponse';
import { GetAllEmailMessagesResponse } from '../model/getAllEmailMessagesResponse';
import { GetEmailMessageResponse } from '../model/getEmailMessageResponse';
import { SearchEmailMessageRequest } from '../model/searchEmailMessageRequest';
import { SearchEmailMessageResponse } from '../model/searchEmailMessageResponse';
import { SendEmailRequest } from '../model/sendEmailRequest';
import { SendEmailResponse } from '../model/sendEmailResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class EmailMessageService {

    protected basePath = 'https://localhost:44349';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Adds new email message
     * 
     * @param request {NSI.DataContracts.Notifications.EmailMessage.AddEmailMessageRequest}
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailMessageAdd(request: AddEmailMessageRequest, observe?: 'body', reportProgress?: boolean): Observable<AddEmailMessageResponse>;
    public emailMessageAdd(request: AddEmailMessageRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AddEmailMessageResponse>>;
    public emailMessageAdd(request: AddEmailMessageRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AddEmailMessageResponse>>;
    public emailMessageAdd(request: AddEmailMessageRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling emailMessageAdd.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<AddEmailMessageResponse>(`${this.basePath}/api/EmailMessage/Add`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Deletes email message
     * 
     * @param id {NSI.DataContracts.Notifications.EmailMessage.DeleteEmailMessageRequest}
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailMessageDeleteById(id: number, observe?: 'body', reportProgress?: boolean): Observable<DeleteEmailMessageResponse>;
    public emailMessageDeleteById(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DeleteEmailMessageResponse>>;
    public emailMessageDeleteById(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DeleteEmailMessageResponse>>;
    public emailMessageDeleteById(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling emailMessageDeleteById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<DeleteEmailMessageResponse>(`${this.basePath}/api/EmailMessage/DeleteById/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves all email messages
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailMessageGetAll(observe?: 'body', reportProgress?: boolean): Observable<GetAllEmailMessagesResponse>;
    public emailMessageGetAll(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetAllEmailMessagesResponse>>;
    public emailMessageGetAll(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetAllEmailMessagesResponse>>;
    public emailMessageGetAll(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];

        return this.httpClient.get<GetAllEmailMessagesResponse>(`${this.basePath}/api/EmailMessage/GetAll`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves a single email message by provided ID in request
     * 
     * @param id {NSI.DataContracts.Notifications.EmailMessage.GetEmailMessageRequest}
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailMessageGetById(id: number, observe?: 'body', reportProgress?: boolean): Observable<GetEmailMessageResponse>;
    public emailMessageGetById(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetEmailMessageResponse>>;
    public emailMessageGetById(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetEmailMessageResponse>>;
    public emailMessageGetById(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling emailMessageGetById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<GetEmailMessageResponse>(`${this.basePath}/api/EmailMessage/GetById/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Searches email messages. If no parameters have been provided in request, returns all email messages.
     * 
     * @param request 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailMessageSearch(request: SearchEmailMessageRequest, observe?: 'body', reportProgress?: boolean): Observable<SearchEmailMessageResponse>;
    public emailMessageSearch(request: SearchEmailMessageRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SearchEmailMessageResponse>>;
    public emailMessageSearch(request: SearchEmailMessageRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SearchEmailMessageResponse>>;
    public emailMessageSearch(request: SearchEmailMessageRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling emailMessageSearch.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<SearchEmailMessageResponse>(`${this.basePath}/api/EmailMessage/Search`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Sends email message with SMTP, body: {}
     * 
     * @param request {NSI.DataContracts.Notifications.EmailMessage.SendEmailRequest}
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailMessageSendMailSMTP(request: SendEmailRequest, observe?: 'body', reportProgress?: boolean): Observable<SendEmailResponse>;
    public emailMessageSendMailSMTP(request: SendEmailRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SendEmailResponse>>;
    public emailMessageSendMailSMTP(request: SendEmailRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SendEmailResponse>>;
    public emailMessageSendMailSMTP(request: SendEmailRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling emailMessageSendMailSMTP.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<SendEmailResponse>(`${this.basePath}/api/EmailMessage/SendMailSMTP`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Sends email message with SendGrid, body: {}
     * 
     * @param request {NSI.DataContracts.Notifications.EmailMessage.SendEmailRequest}
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public emailMessageSendMailSendGrid(request: SendEmailRequest, observe?: 'body', reportProgress?: boolean): Observable<SendEmailResponse>;
    public emailMessageSendMailSendGrid(request: SendEmailRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SendEmailResponse>>;
    public emailMessageSendMailSendGrid(request: SendEmailRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SendEmailResponse>>;
    public emailMessageSendMailSendGrid(request: SendEmailRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling emailMessageSendMailSendGrid.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<SendEmailResponse>(`${this.basePath}/api/EmailMessage/SendMailSendGrid`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
