/**
 * NSI.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { IncidentSettlementDomain } from '../model/incidentSettlementDomain';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class IncidentSettlementService {

    protected basePath = 'https://localhost:44349';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Adds new incident
     * 
     * @param incidentSettlement 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public incidentSettlementAddIncidentSettlement(incidentSettlement: IncidentSettlementDomain, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public incidentSettlementAddIncidentSettlement(incidentSettlement: IncidentSettlementDomain, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public incidentSettlementAddIncidentSettlement(incidentSettlement: IncidentSettlementDomain, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public incidentSettlementAddIncidentSettlement(incidentSettlement: IncidentSettlementDomain, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (incidentSettlement === null || incidentSettlement === undefined) {
            throw new Error('Required parameter incidentSettlement was null or undefined when calling incidentSettlementAddIncidentSettlement.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<number>(`${this.basePath}/api/IncidentSettlement/AddIncidentSettlement`,
            incidentSettlement,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete incident
     * 
     * @param incidentSettlementId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public incidentSettlementDeleteIncidentSettlement(incidentSettlementId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public incidentSettlementDeleteIncidentSettlement(incidentSettlementId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public incidentSettlementDeleteIncidentSettlement(incidentSettlementId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public incidentSettlementDeleteIncidentSettlement(incidentSettlementId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (incidentSettlementId === null || incidentSettlementId === undefined) {
            throw new Error('Required parameter incidentSettlementId was null or undefined when calling incidentSettlementDeleteIncidentSettlement.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (incidentSettlementId !== undefined) {
            queryParameters = queryParameters.set('incidentSettlementId', <any>incidentSettlementId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/IncidentSettlement/DeleteIncidentSettlement`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Edit incident
     * 
     * @param incidentSettlement 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public incidentSettlementEditIncidentSettlement(incidentSettlement: IncidentSettlementDomain, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public incidentSettlementEditIncidentSettlement(incidentSettlement: IncidentSettlementDomain, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public incidentSettlementEditIncidentSettlement(incidentSettlement: IncidentSettlementDomain, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public incidentSettlementEditIncidentSettlement(incidentSettlement: IncidentSettlementDomain, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (incidentSettlement === null || incidentSettlement === undefined) {
            throw new Error('Required parameter incidentSettlement was null or undefined when calling incidentSettlementEditIncidentSettlement.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/IncidentSettlement/EditIncidentSettlement`,
            incidentSettlement,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves all incidents settlements from system
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public incidentSettlementGet(observe?: 'body', reportProgress?: boolean): Observable<Array<IncidentSettlementDomain>>;
    public incidentSettlementGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<IncidentSettlementDomain>>>;
    public incidentSettlementGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<IncidentSettlementDomain>>>;
    public incidentSettlementGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<IncidentSettlementDomain>>(`${this.basePath}/api/IncidentSettlement/Get`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves incident settlement by provided id
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public incidentSettlementGet_1(id: number, observe?: 'body', reportProgress?: boolean): Observable<IncidentSettlementDomain>;
    public incidentSettlementGet_1(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IncidentSettlementDomain>>;
    public incidentSettlementGet_1(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IncidentSettlementDomain>>;
    public incidentSettlementGet_1(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling incidentSettlementGet_1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<IncidentSettlementDomain>(`${this.basePath}/api/IncidentSettlement/Get/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
