/**
 * NSI.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { AddLanguageRequest } from '../model/addLanguageRequest';
import { AddLanguageResponse } from '../model/addLanguageResponse';
import { GetLanguageResponse } from '../model/getLanguageResponse';
import { SearchLanguagesRequest } from '../model/searchLanguagesRequest';
import { SearchLanguagesResponse } from '../model/searchLanguagesResponse';
import { UpdateLanguageRequest } from '../model/updateLanguageRequest';
import { UpdateLanguageResponse } from '../model/updateLanguageResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class LanguageService {

    protected basePath = 'https://localhost:44349';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Adds new language
     * 
     * @param request {NSI.DataContracts.Membership.Languages.AddLanguageRequest}
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public languageAddLanguage(request: AddLanguageRequest, observe?: 'body', reportProgress?: boolean): Observable<AddLanguageResponse>;
    public languageAddLanguage(request: AddLanguageRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AddLanguageResponse>>;
    public languageAddLanguage(request: AddLanguageRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AddLanguageResponse>>;
    public languageAddLanguage(request: AddLanguageRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling languageAddLanguage.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<AddLanguageResponse>(`${this.basePath}/api/Language/AddLanguage`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves single language by provided ID in request
     * 
     * @param id {NSI.DataContracts.Membership.Languages.GetLanguageRequest}
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public languageGetLanguage(id: number, observe?: 'body', reportProgress?: boolean): Observable<GetLanguageResponse>;
    public languageGetLanguage(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetLanguageResponse>>;
    public languageGetLanguage(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetLanguageResponse>>;
    public languageGetLanguage(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling languageGetLanguage.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<GetLanguageResponse>(`${this.basePath}/api/Language/GetLanguage/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Searches languages. If no parameters have been provided in request, return all languages.
     * 
     * @param request {NSI.DataContracts.Membership.Languages.SearchLanguagesRequest}
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public languageSearchLanguages(request: SearchLanguagesRequest, observe?: 'body', reportProgress?: boolean): Observable<SearchLanguagesResponse>;
    public languageSearchLanguages(request: SearchLanguagesRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SearchLanguagesResponse>>;
    public languageSearchLanguages(request: SearchLanguagesRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SearchLanguagesResponse>>;
    public languageSearchLanguages(request: SearchLanguagesRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling languageSearchLanguages.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<SearchLanguagesResponse>(`${this.basePath}/api/Language/SearchLanguages`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Updates language
     * 
     * @param request {NSI.DataContracts.Membership.Languages.UpdateLanguageRequest}
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public languageUpdateLanguage(request: UpdateLanguageRequest, observe?: 'body', reportProgress?: boolean): Observable<UpdateLanguageResponse>;
    public languageUpdateLanguage(request: UpdateLanguageRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UpdateLanguageResponse>>;
    public languageUpdateLanguage(request: UpdateLanguageRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UpdateLanguageResponse>>;
    public languageUpdateLanguage(request: UpdateLanguageRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling languageUpdateLanguage.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<UpdateLanguageResponse>(`${this.basePath}/api/Language/UpdateLanguage`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
