/**
 * NSI.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { AddPermissionRequest } from '../model/addPermissionRequest';
import { AddPermissionResponse } from '../model/addPermissionResponse';
import { GetAllPermissionsResponse } from '../model/getAllPermissionsResponse';
import { GetPermissionResponse } from '../model/getPermissionResponse';
import { PermissionForListViewModel } from '../model/permissionForListViewModel';
import { SearchPermissionsRequest } from '../model/searchPermissionsRequest';
import { SearchPermissionsResponse } from '../model/searchPermissionsResponse';
import { UpdatePermissionRequest } from '../model/updatePermissionRequest';
import { UpdatePermissionResponse } from '../model/updatePermissionResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PermissionService {

    protected basePath = 'https://localhost:44349';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Adds new permission
     * 
     * @param request {NSI.DataContracts.Membership.Permissions.AddPermissionRequest}
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public permissionAddPermission(request: AddPermissionRequest, observe?: 'body', reportProgress?: boolean): Observable<AddPermissionResponse>;
    public permissionAddPermission(request: AddPermissionRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AddPermissionResponse>>;
    public permissionAddPermission(request: AddPermissionRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AddPermissionResponse>>;
    public permissionAddPermission(request: AddPermissionRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling permissionAddPermission.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<AddPermissionResponse>(`${this.basePath}/api/Permission/AddPermission`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param searchTerm 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public permissionGet(searchTerm?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<PermissionForListViewModel>>;
    public permissionGet(searchTerm?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PermissionForListViewModel>>>;
    public permissionGet(searchTerm?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PermissionForListViewModel>>>;
    public permissionGet(searchTerm?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (searchTerm !== undefined) {
            queryParameters = queryParameters.set('searchTerm', <any>searchTerm);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<PermissionForListViewModel>>(`${this.basePath}/api/permissions`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves all permissions
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public permissionGetAll(observe?: 'body', reportProgress?: boolean): Observable<GetAllPermissionsResponse>;
    public permissionGetAll(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetAllPermissionsResponse>>;
    public permissionGetAll(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetAllPermissionsResponse>>;
    public permissionGetAll(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];

        return this.httpClient.get<GetAllPermissionsResponse>(`${this.basePath}/api/Permission/GetAll`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves single permission by provided ID in request
     * 
     * @param id {NSI.DataContracts.Membership.Permissions.GetPermissionRequest}
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public permissionGetPermission(id: number, observe?: 'body', reportProgress?: boolean): Observable<GetPermissionResponse>;
    public permissionGetPermission(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetPermissionResponse>>;
    public permissionGetPermission(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetPermissionResponse>>;
    public permissionGetPermission(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling permissionGetPermission.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<GetPermissionResponse>(`${this.basePath}/api/Permission/GetPermission/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Searches permissions. If no parameters have been provided in request, return all permissions.
     * 
     * @param request {NSI.DataContracts.Membership.Permissions.SearchPermissionsRequest}
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public permissionSearchPermissions(request: SearchPermissionsRequest, observe?: 'body', reportProgress?: boolean): Observable<SearchPermissionsResponse>;
    public permissionSearchPermissions(request: SearchPermissionsRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SearchPermissionsResponse>>;
    public permissionSearchPermissions(request: SearchPermissionsRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SearchPermissionsResponse>>;
    public permissionSearchPermissions(request: SearchPermissionsRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling permissionSearchPermissions.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<SearchPermissionsResponse>(`${this.basePath}/api/Permission/SearchPermissions`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Updates permission
     * 
     * @param request {NSI.DataContracts.Membership.Permissions.UpdatePermissionRequest}
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public permissionUpdatePermission(request: UpdatePermissionRequest, observe?: 'body', reportProgress?: boolean): Observable<UpdatePermissionResponse>;
    public permissionUpdatePermission(request: UpdatePermissionRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UpdatePermissionResponse>>;
    public permissionUpdatePermission(request: UpdatePermissionRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UpdatePermissionResponse>>;
    public permissionUpdatePermission(request: UpdatePermissionRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling permissionUpdatePermission.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<UpdatePermissionResponse>(`${this.basePath}/api/Permission/UpdatePermission`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
